spring:
  application:
    name: service-code
  datasource:
    url: jdbc:mysql://localhost:3306/lagou_springcloud?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/ #把 eureka 集群中的所有 url 都填写了进来，也可以只写一台，因为各个 eureka server 可以同步注册表
    instance:
      prefer-ip-address: true #使用ip注册

server:
  port: 8081
management:
  endpoints:
  web:
  exposure:
  include: refresh
