spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/lagou_springcloud?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
server:
  port: 8080

management:
  endpoints:
  web:
  exposure:
  include: refresh